---
#Copiando arquivos   
- name: COPY | Copiando arquivo 
  win_copy:
    src: "{{ file }}"
    dest: "{{ folder }}"
 
#Extraindo arquivos 
- name: Extraindo arquivos copiados
  community.windows.win_unzip:
    src: "{{folder}}{{file}}"
    dest: "{{folder}}{{version}}"
    #password: abcd
    #delete_archive: yes

#Rename folder
- name: rename the {{ appOldName }} to  {{ appName }}
  win_command: "cmd.exe /c rename {{ folder }}{{ version }}{{ appOldName }} {{ appName }}"

#Stop Pool da Versao 
- name: Stop Pool da Versao
  community.windows.win_iis_webapppool:
    name: "{{ appName }}{{ client }}App"
    state: stopped

#Powershell com parametros para fazer backup dos arquivos antigos
- name: Copy Files for backup
  ansible.windows.win_powershell:
    script: |
      [CmdletBinding()]
      param (
          [String]
          $Folder,

          [String]
          $FolderBackup,

          [Switch]
          $Force
      )
      
      if(Test-Path ($FolderBackup)){
        Remove-Item -Path $FolderBackup -Recurse -Force:$Force
      } 
      if(-not (Test-Path ($FolderBackup))){
        New-Item -ItemType "directory" -Path $FolderBackup 
      }   
       
      Get-ChildItem -Path $Folder -Recurse -Exclude "Backup\" |  Move-Item -Destination $FolderBackup
      
    parameters:
      Folder: "{{ folderIIS }}{{ version }}{{ appName }}"
      FolderBackup: "{{ folderIIS }}{{ version }}{{ appName }}\\Backup\\"
      Force: true  

#Powershell com parametros para copia dos arquivos
- name: Copy Files for IIS
  ansible.windows.win_powershell:
    script: |
      [CmdletBinding()]
      param (
          [String]
          $Folder,

          [String]
          $FolderIIS
      )
      Copy-Item -Path $Folder -Destination $FolderIIS -Recurse

    parameters:
      Folder: "{{ folder }}{{ version }}"
      FolderIIS: "{{ folderIIS }}"
     # Force: true

#Start Pool da Versao 
- name: Start Pool da Versao
  community.windows.win_iis_webapppool:
    name: "{{ appName }}{{ client }}App"
    state: started


#Powershell Remover arquivos antigos com parametros 
- name: Clear Files for folder
  ansible.windows.win_powershell:
    script: |
      [CmdletBinding()]
      param (
          [String]
          $Folder,

          [Switch]
          $Force
      )
      Remove-Item -Path $Folder -Recurse -Force:$Force

    parameters:
      Folder: "{{ folder }}"
     # FolderIIS: "{{ folderIIS }}"
      Force: true
...
