---
#Copiando arquivos   
- name: COPY | Copiando arquivo 
  win_copy:
    src: "{{ file }}"
    dest: "{{ folder }}"
 
#Extraindo arquivos 
- name: Extraindo arquivos copiados
  community.windows.win_unzip:
    src: "{{folder}}{{file}}"
    dest: "{{folder}}{{version}}"
    #password: abcd
    delete_archive: yes

#Rename folder
- name: rename the {{ appOldName }} to  {{ appName }}
  win_command: "cmd.exe /c rename {{ folder }}{{ version }}{{ appOldName }} {{ appName }}"

#Powershell com parametros para copia dos arquivos
- name: Copy Files for IIS
  ansible.windows.win_powershell:
    script: |
      [CmdletBinding()]
      param (
          [String]
          $Folder,

          [String]
          $FolderIIS
      )
      Copy-Item -Path $Folder -Destination $FolderIIS -Recurse

    parameters:
      Folder: "{{ folder }}{{ version }}"
      FolderIIS: "{{ folderIIS }}"
     # Force: true

#Creação do Pool do IIS
- name: Creates an application pool, sets attributes and starts it
  community.windows.win_iis_webapppool:
    name: "{{ versionPool }}"
    state: started
    attributes:
      managedRuntimeVersion: v4.0
      autoStart: yes

#Configuracao do Pool do IIS
- name: Configuration on application pool, sets attributes and starts it
  community.windows.win_iis_webapppool:
    name: "{{ versionPool }}"
    state: started
    attributes:
      enable32BitAppOnWin64: yes
      startMode: 1
      processModel.maxProcesses: 0
      recycling.periodicRestart.time: "01:00:00" 


#Criacao do Site da Versao
- name: Add Site on IIS
  community.windows.win_iis_webapplication:
    name: "{{ appName }}"
    site: "{{ siteDefault }}//{{ versionPool }}"
    state: present
    physical_path: "{{ folderIIS }}{{ version }}{{ appName }}"
    application_pool: "{{ versionPool }}"

#Powershell Remover arquivos antigos com parametros 
- name: Clear Files for folder
  ansible.windows.win_powershell:
    script: |
      [CmdletBinding()]
      param (
          [String]
          $Folder,

          [Switch]
          $Force
      )
      Remove-Item -Path $Folder -Recurse -Force:$Force

    parameters:
      Folder: "{{ folder }}"
     # FolderIIS: "{{ folderIIS }}"
      Force: true
...
