---
#Gerenciamento de pacotes e atualização do sistema operacional
- name: Atualizacao do sistema operacional
  apt: name=* state=latest update_cache=yes
  
- name: instalacao de pacotes
  apt: 
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - net-tools
      - vim
      - tree 

#Configurando TimeZone
- name: Configurando Timezone
  file: src=/usr/share/zoneinfo/America/Sao_Paulo dest=/etc/localtime state=link force=yes

#Copia de arquivo
- name: Copiando arquivo de backup
  copy: src=backup.tar.xz dest=/tmp/backup.tar.xz

- name: Copiando um template
  template: src=motd dest=/etc/motd force=yes owner=root group=root

  #Instalacao Nginx
- name: Instalacao Nginx
  apt: name=nginx state=latest
  notify: Restart Nginx
...