---

#Rename folder
#Powershell com parametros para Renomear
- name: Copy Files for IIS
  ansible.windows.win_powershell:
    script: |
      [CmdletBinding()]
      param (
          [String]
          $File,

          [String]
          $FileOld,

          [String]
          $FileOldTest
      )
      if(Test-Path $FileOldTest -PathType Leaf){

        Remove-Item -Path $FileOldTest 
    
      }
      Rename-Item -Path $File -NewName $FileOld 

    parameters:
      File: "{{ folder }}{{ file }}"
      FileOld: "{{ fileOld }}"
      FileOldTest: "{{ folder }}{{ fileOld }}"
     # Force: true

#Copiando arquivos   
- name: COPY | Copiando arquivo 
  win_copy:
    src: "{{ file }}"
    dest: "{{ folder }}"

#Restart Pool da Versao 
- name: Restart Pool da Versao
  community.windows.win_iis_webapppool:
    name: "{{ iisPool }}"
    state: restarted

...
