---
file: ServicosDbTopManager.zip
folder: C:\Users\Public\Documents\temp\
folderIIS: C:\inetpub\wwwroot\
version: 2801000\
versionPool: 2801000
siteDefault: Default Web Site
appOldName: ServicosDbTopManager
appName: DbTopManagerServicos
...